# Reihan Al Sya'Ban
# 2109106051
# POSTTEST 7 TENSORFLOW

## Import Library TensorFlow

In [1]:
import tensorflow as tf

## Membuat variabel random_tensor & prime_tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean = 2, stddev = 1, seed = 1)
random_tensor.numpy()

array([[ 1.1886818 ,  3.4845986 ,  2.0653293 , -0.4427042 ,  2.0992484 ],
       [ 2.5912242 ,  2.592823  , -0.12292957,  1.2771027 ,  1.9437296 ],
       [ 2.6435447 ,  1.7356759 ,  3.8566332 ,  2.5678418 ,  1.6171641 ],
       [ 0.51465666,  3.2617712 ,  1.9746939 ,  1.7353703 ,  3.5328138 ],
       [ 0.25702286,  1.5621071 ,  1.43399   ,  2.3206692 ,  3.132831  ]],
      dtype=float32)

In [3]:
prime_tensor = tf.constant([2,3,5,7,11,13,17,19,23,29,31,37,41,43,47,53,59,61,71,73,79,83,89,97,101],shape=(5,5),dtype=tf.float32)
prime_tensor.numpy()

array([[  2.,   3.,   5.,   7.,  11.],
       [ 13.,  17.,  19.,  23.,  29.],
       [ 31.,  37.,  41.,  43.,  47.],
       [ 53.,  59.,  61.,  71.,  73.],
       [ 79.,  83.,  89.,  97., 101.]], dtype=float32)

## Dimensi dari random_tensor & prime_tensor

In [4]:
print("random_tensor : ", random_tensor.shape)
print("prime_tensor  : ", prime_tensor.shape)

random_tensor :  (5, 5)
prime_tensor  :  (5, 5)


## Perhitungan Aritmatika antara random_tensor & prime_tensor

In [5]:
print("Penjumlahan :\n", tf.add(random_tensor,prime_tensor).numpy())

Penjumlahan :
 [[  3.1886818   6.4845986   7.0653296   6.557296   13.099249 ]
 [ 15.591225   19.592823   18.877071   24.277103   30.94373  ]
 [ 33.643543   38.735676   44.856632   45.56784    48.617165 ]
 [ 53.514656   62.261772   62.974693   72.73537    76.532814 ]
 [ 79.25702    84.5621     90.43399    99.32067   104.13283  ]]


In [6]:
print("Pengurangan :\n", tf.subtract(random_tensor,prime_tensor).numpy())

Pengurangan :
 [[ -0.81131816   0.48459864  -2.9346707   -7.442704    -8.900751  ]
 [-10.408775   -14.407177   -19.122929   -21.722897   -27.05627   ]
 [-28.356455   -35.264324   -37.143368   -40.43216    -45.382835  ]
 [-52.485344   -55.738228   -59.025307   -69.26463    -69.467186  ]
 [-78.74298    -81.4379     -87.56601    -94.67933    -97.86717   ]]


In [7]:
print("Perkalian matriks :\n", tf.matmul(random_tensor,prime_tensor).numpy())

Perkalian matriks :
 [[254.07965 287.33948 316.65744 349.4708  390.906  ]
 [256.3194  283.9819  308.07486 351.70358 387.46283]
 [411.25812 465.85983 504.88348 563.44226 611.46136]
 [475.71478 525.66815 565.7874  629.4294  676.55945]
 [435.76425 477.32898 510.14154 568.0413  601.3507 ]]


In [8]:
print("Perkalian :\n", tf.multiply(random_tensor,prime_tensor).numpy())

Perkalian :
 [[  2.3773637  10.453796   10.326647   -3.0989294  23.091732 ]
 [ 33.685913   44.07799    -2.335662   29.373362   56.36816  ]
 [ 81.94988    64.22001   158.12196   110.4172     76.006714 ]
 [ 27.276804  192.4445    120.45633   123.21129   257.89542  ]
 [ 20.304806  129.65489   127.62511   225.1049    316.41595  ]]


In [9]:
print("Pembagian :\n", tf.divide(random_tensor,prime_tensor).numpy())

Pembagian :
 [[ 0.5943409   1.1615329   0.41306585 -0.06324346  0.19084077]
 [ 0.19932494  0.152519   -0.00646998  0.0555262   0.06702516]
 [ 0.08527564  0.04691016  0.09406422  0.05971725  0.03440775]
 [ 0.0097105   0.05528426  0.03237203  0.02444183  0.04839471]
 [ 0.00325345  0.01882057  0.01611225  0.02392443  0.03101813]]


In [10]:
print("Pangkat :\n", tf.pow(random_tensor,prime_tensor).numpy())

Pangkat :
 [[ 1.41296446e+00  4.23114853e+01  3.75791130e+01 -3.33269453e-03
   3.48900952e+03]
 [ 2.37446000e+05  1.08177980e+07 -5.05208996e-18  2.77455933e+02
   2.34660432e+08]
 [ 1.22401367e+13  7.25002880e+08  1.08278367e+24  4.08728707e+17
   6.47802675e+09]
 [ 5.13372693e-16  1.96678162e+30  1.06044165e+18  9.92757123e+16
              inf]
 [ 0.00000000e+00  1.19673122e+16  8.56258689e+13  2.91396052e+35
              inf]]


## Nilai Maksimal & Minimal dari random_tensor

In [11]:
print("Maksimal : ", tf.reduce_max(random_tensor).numpy())

Maksimal :  3.8566332


In [12]:
print("Minimal  : ", tf.reduce_min(random_tensor).numpy())

Minimal  :  -0.4427042


## Penggabungan random_tensor & prime_tensor

In [17]:
concat = tf.concat([random_tensor,prime_tensor], axis = 1)
concat.numpy()

array([[  1.1886818 ,   3.4845986 ,   2.0653293 ,  -0.4427042 ,
          2.0992484 ,   2.        ,   3.        ,   5.        ,
          7.        ,  11.        ],
       [  2.5912242 ,   2.592823  ,  -0.12292957,   1.2771027 ,
          1.9437296 ,  13.        ,  17.        ,  19.        ,
         23.        ,  29.        ],
       [  2.6435447 ,   1.7356759 ,   3.8566332 ,   2.5678418 ,
          1.6171641 ,  31.        ,  37.        ,  41.        ,
         43.        ,  47.        ],
       [  0.51465666,   3.2617712 ,   1.9746939 ,   1.7353703 ,
          3.5328138 ,  53.        ,  59.        ,  61.        ,
         71.        ,  73.        ],
       [  0.25702286,   1.5621071 ,   1.43399   ,   2.3206692 ,
          3.132831  ,  79.        ,  83.        ,  89.        ,
         97.        , 101.        ]], dtype=float32)

## Sorting random_tensor, prime_tensor, dan Gabungan kedua Variabel

### random_tensor

In [18]:
sort_random = tf.sort(random_tensor, direction = 'DESCENDING')
sort_random.numpy()

array([[ 3.4845986 ,  2.0992484 ,  2.0653293 ,  1.1886818 , -0.4427042 ],
       [ 2.592823  ,  2.5912242 ,  1.9437296 ,  1.2771027 , -0.12292957],
       [ 3.8566332 ,  2.6435447 ,  2.5678418 ,  1.7356759 ,  1.6171641 ],
       [ 3.5328138 ,  3.2617712 ,  1.9746939 ,  1.7353703 ,  0.51465666],
       [ 3.132831  ,  2.3206692 ,  1.5621071 ,  1.43399   ,  0.25702286]],
      dtype=float32)

### prime_tensor

In [19]:
sort_prime = tf.sort(prime_tensor, direction = 'DESCENDING')
sort_prime.numpy()

array([[ 11.,   7.,   5.,   3.,   2.],
       [ 29.,  23.,  19.,  17.,  13.],
       [ 47.,  43.,  41.,  37.,  31.],
       [ 73.,  71.,  61.,  59.,  53.],
       [101.,  97.,  89.,  83.,  79.]], dtype=float32)

### Gabungan kedua variabel

In [20]:
sort_concat  = tf.sort(concat, direction = 'DESCENDING')
sort_concat.numpy()

array([[ 11.        ,   7.        ,   5.        ,   3.4845986 ,
          3.        ,   2.0992484 ,   2.0653293 ,   2.        ,
          1.1886818 ,  -0.4427042 ],
       [ 29.        ,  23.        ,  19.        ,  17.        ,
         13.        ,   2.592823  ,   2.5912242 ,   1.9437296 ,
          1.2771027 ,  -0.12292957],
       [ 47.        ,  43.        ,  41.        ,  37.        ,
         31.        ,   3.8566332 ,   2.6435447 ,   2.5678418 ,
          1.7356759 ,   1.6171641 ],
       [ 73.        ,  71.        ,  61.        ,  59.        ,
         53.        ,   3.5328138 ,   3.2617712 ,   1.9746939 ,
          1.7353703 ,   0.51465666],
       [101.        ,  97.        ,  89.        ,  83.        ,
         79.        ,   3.132831  ,   2.3206692 ,   1.5621071 ,
          1.43399   ,   0.25702286]], dtype=float32)